### ISSUE TITLE
setStatusCode error, signature mismatch

### ISSUE THREAD

**Issue by novacp** [bshaffer/oauth2-server-httpfoundation-bridge#31]
Using the latest stable HttpFoundation component, I get an error when trying to implement the ResponseInterface or when using this library: 
**setStatusCode(...) signature does not match the expected one from HttpFoundation.**

This blocks the whole library.

Best regards.

**Comment by peluprvi** [comment]
Same issue here after upgrade to Laravel 5.6

**Comment by peluprvi** [comment]
It worked here by changing `OAuth2/HttpFoundationBridge/Response` to `OAuth2/Response`

**Comment by novacp** [comment]
Yes, the Problem lays within the core library interface, so your workaround (and mine too) is to not use this bridge anymore until updated.

Regards

Von: Pedro Vieira
Gesendet: Freitag, 9. Februar 2018 16:57
An: bshaffer/oauth2-server-httpfoundation-bridge
Cc: novacp; Author
Betreff: Re: [bshaffer/oauth2-server-httpfoundation-bridge] setStatusCodeerror, signature mismatch (#31)

It worked here by changing OAuth2/HttpFoundationBridge/Response to OAuth2/Response

**Comment by mariendev** [comment]
I did some manual fixes in the library when experiencing this issue. Hoping for an official fix!

**Comment by reb3r** [comment]
The core Problem is a BC [here](https://github.com/symfony/http-foundation/blob/014487772c22d893168e5d628a13e882009fea29/Response.php#L438) in the http-foundation library > 4.0. They inserted a type declaration in this method which leads to an incompatibility to the [core library](https://github.com/bshaffer/oauth2-server-php/blob/061f81496dbe52fc0514c1642b366eac1b125310/src/OAuth2/ResponseInterface.php#L26) which don't use type declaration because they are only available since PHP 7.0. You can try to force your projects to use symfony/http-foundation with version constraint "~3.3" or change the code of the ResponseInterface to use type declaration.

**Comment by bshaffer** [comment]
This is still not completely fixed, as a warning is still thrown in PHP 7.1 (but not in PHP 7.2). 

At least now it's not a fatal error, and it's fixed in PHP 7.2. I'll continue to look into a more complete fix.

**Comment by araab** [comment]
This issue was fixed in https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/pull/37
@bshaffer Can you please tag a new release?

**Comment by harshitchaudhary** [comment]
_@bshaffer  Can you please tag a new release?_ 

Looking forward for this release.

**Comment by bshaffer** [comment]
> _@bshaffer  Can you please tag a new release?_ 
> 
> Looking forward for this release. 
> 

@harshitchaudhary  Done!

https://github.com/bshaffer/oauth2-server-httpfoundation-bridge/releases/tag/v1.5
